baseURL = "https://totland.dev/"
title = "totland.dev"

pygmentsCodeFences = true
googleAnalytics = "UA-143827897-1"

[author]
  name = "Karl H. Totland"       #Author name
  github = "karlhto"     #Github username
  gitlab = "karlhto"     #Gitlab username
  linkedin = "karl-h-totland-520583133"   #LinkedIn username
  facebook = ""   #Facebook username
  twitter = ""    #Twitter username
  instagram = ""  #Instagram username

[params]
  AuthorName = "Karl H. Totland"
  GitHubUser = "karlhto"

[permalinks]
  post = "/:year/:month/:day/:slug/"
